### ISSUE TITLE
Laird RG1xx Gateway Issues

### ISSUE THREAD

**Issue by baxterjo** [aws-samples/aws-iot-core-lorawan#1]
Hello,

I would first like to start by saying I recognize that this is a brand new service, so I am more than patient in exploring and adopting this into my existing AWS architecture. I am excited that AWS is hosting a service such as this. It was a "right time/ right place" release as I had been exploring the Chirpstack LNS for only 5 days and had been trying to figure out how to integrate it into our architecture when the announcement for IoT Core for LoRaWAN came out.

## Issue
I am folloing the provided [AWS documentation](https://docs.aws.amazon.com/iot/latest/developerguide/connect-iot-lorawan.html?icmpid=docs_iot_console) in conjunction with the [Laird documentation](https://www.lairdconnect.com/documentation/coming-soon-application-note-rg1xx-aws-iot-core-lorawan) and have added a gateway to IoT Core. However, the gateway is not appearing as connected when I visit the gateway web interface. Nor has it been "seen" by IoT Core. I found an inconsistency with the IAM policy AWS manages and the policy that *Laird* recommends using.
### AWS Managed Policy
```json
{
    "Version": "2012-10-17",
    "Statement": [
          {
          "Sid": "IoTWirelessGatewayCertManager",
          "Effect": "Allow",
          "Action": [
          "iot:CreateKeysAndCertificate",
          "iot:DescribeCertificate",
          "iot:ListCertificates"
          ],
          "Resource": "*"
          }
    ]
}
```

### Laird Recommended Policy (Page 5 of the [Laird document](https://www.lairdconnect.com/documentation/coming-soon-application-note-rg1xx-aws-iot-core-lorawan))
```json
{
    "Version": "2012-10-17",
    "Statement": [
          {
          "Sid": "IoTWirelessGatewayCertManager",
          "Effect": "Allow",
          "Action": [
          "iot:CreateKeysAndCertificate",
          "iot:DescribeCertificate",
          "iot:ListCertificates",
          "iot:RegisterCertificate"
          ],
          "Resource": "*"
          }
    ]
}
```
I added both policies to the `AWSIoTWirelessGatewayCertManagerRole` that is common in *both* guides. 

I continued along with the [Laird document](https://www.lairdconnect.com/documentation/coming-soon-application-note-rg1xx-aws-iot-core-lorawan) down to section 5.3.6 following their provided instructions very carefully but have not been able to connect.

In the logs of the Laird device I am met with this repeating message:
```log

RG1xx29F02D | lora | user.notice | Dec 16 18:34:16 | key usage : Digital Signature, Key Cert Sign, CRL Sign
-- | -- | -- | -- | --
RG1xx29F02D | lora | user.notice | Dec 16 18:34:16 | basic constraints : CA=true, max_pathlen=0
RG1xx29F02D | lora | user.notice | Dec 16 18:34:16 | RSA key size : 2048 bits
RG1xx29F02D | lora | user.notice | Dec 16 18:34:16 | signed using : RSA with SHA-256
RG1xx29F02D | lora | user.notice | Dec 16 18:34:16 | expires on : 2025-10-19 00:00:00
RG1xx29F02D | lora | user.notice | Dec 16 18:34:16 | issued on : 2015-10-22 00:00:00
RG1xx29F02D | lora | user.notice | Dec 16 18:34:16 | subject name : C=US, O=Amazon, OU=Server CA 1B, CN=Amazon
RG1xx29F02D | lora | user.notice | Dec 16 18:34:16 | issuer name : C=US, O=Amazon, CN=Amazon Root CA 1
RG1xx29F02D | lora | user.notice | Dec 16 18:34:16 | serial number : 06:7F:94:57:85:87:E8:AC:77:DE:B2:53:32:5B:BC:99:8B:56:0D
RG1xx29F02D | lora | user.notice | Dec 16 18:34:16 | 2020-12-16 18:34:15.172 [any:INFO] cert. version : 3
RG1xx29F02D | lora | user.notice | Dec 16 18:34:16 | 2020-12-16 18:34:15.171 [CUP:INFO] Connecting to CUPS-boot ... https://A3IULHZA88PP87.cups.lorawan.us-east-1.amazonaws.com:443 (try #1456)
RG1xx29F02D | lora | user.notice | Dec 16 18:34:16 | 2020-12-16 18:34:15.171 [CUP:INFO] Starting a CUPS session now.
RG1xx29F02D | lora | user.notice | Dec 16 18:34:16 | 2020-12-16 18:34:15.170 [CUP:INFO] Starting a CUPS session in 0 seconds.
RG1xx29F02D | lora | user.notice | Dec 16 18:34:14 | 2020-12-16 18:34:14.170 [CUP:ERRO] No CUPS-bak URI configured
RG1xx29F02D | lora | user.notice | Dec 16 18:34:14 | 2020-12-16 18:34:14.170 [CUP:INFO] Starting a CUPS session now.
RG1xx29F02D | lora | user.notice | Dec 16 18:34:14 | 2020-12-16 18:34:14.169 [CUP:INFO] Starting a CUPS session in 0 seconds.
RG1xx29F02D | lora | user.notice | Dec 16 18:34:13 | 2020-12-16 18:34:13.161 [CUP:INFO] Interaction with CUPS failed - retrying in 1s
RG1xx29F02D | lora | user.notice | Dec 16 18:34:13 | 2020-12-16 18:34:13.160 [AIO:DEBU] [3] HTTP connection shutdown...
RG1xx29F02D | lora | user.notice | Dec 16 18:34:13 | 2020-12-16 18:34:13.159 [AIO:ERRO] [3] Send failed: NET - Connection was reset by peer
RG1xx29F02D | lora | user.notice | Dec 16 18:34:12 | 2020-12-16 18:34:11.896 [CUP:VERB] Retrieving update-info from CUPS https://A3IULHZA88PP87.cups.lorawan.us-east-1.amazonaws.com:443...
RG1xx29F02D | lora | user.notice | Dec 16 18:34:12 | 2020-12-16 18:34:11.808 [AIO:INFO]
RG1xx29F02D | lora | user.notice | Dec 16 18:34:12 | key usage : Digital Signature
RG1xx29F02D | lora | user.notice | Dec 16 18:34:12 | basic constraints : CA=false
RG1xx29F02D | lora | user.notice | Dec 16 18:34:12 | RSA key size : 2048 bits
RG1xx29F02D | lora | user.notice | Dec 16 18:34:12 | signed using : RSA with SHA-256
RG1xx29F02D | lora | user.notice | Dec 16 18:34:12 | expires on : 2049-12-31 23:59:59
RG1xx29F02D | lora | user.notice | Dec 16 18:34:12 | issued on : 2020-12-15 22:43:47
RG1xx29F02D | lora | user.notice | Dec 16 18:34:12 | subject name : CN=AWS IoT Certificate
RG1xx29F02D | lora | user.notice | Dec 16 18:34:12 | issuer name : OU=Amazon Web Services O=Amazon.com Inc. L=Seattle ST=Washington C=US
RG1xx29F02D | lora | user.notice | Dec 16 18:34:12 | serial number : 13:5D:82:86:E9:A7:A4:69:5A:1F:E5:F4:5E:1F:E3:71:5A:DD:4E:FC
RG1xx29F02D | lora | user.notice | Dec 16 18:34:12 | 2020-12-16 18:34:11.808 [any:INFO] cert. version : 3
RG1xx29F02D | lora | user.notice | Dec 16 18:34:12 | key usage : Digital Signature, Key Cert Sign, CRL Sign

```

And this is where I am stuck. Normally I would not submit a ticket in AWS for a hardware interface problem, but the logs have this message: `RG1xx29F02D | lora | user.notice | Dec 16 18:34:13 | 2020-12-16 18:34:13.159 [AIO:ERRO] [3] Send failed: NET - Connection was reset by peer` which could be an AWS issue. Also the Laird gateway is on the list of AWS certified devices, so that implies some responsibility on AWS to ensure the gateway works with IoT Core for LoRaWAN.

### What I have tried
The CUPS and LNS certificate uploads in the Laird Basic Station setup page seemed a little fishy on what cert goes where. So I tried swapping the `<type>.trust` and the `.PEM` certificate for both, but that gives me a hard "certificate invalid" log message. So that is working as expected.

### Next Steps
My next step is to get the logging info from AWS IoT. I will edit this posting with my results.

### Version Information
I am adding the gateway and creating IAM roles through the AWS console.
Laird FW Version is `Laird Linux gatwick-laird-93.9.5.7`

**Comment by baxterjo** [comment]
## Update
I was unable to get the logs to Cloudwatch. I followed the setup guide [here](https://docs.aws.amazon.com/iot/latest/developerguide/configure-logging.html) and set the logging level to debug. No events are going to the logs.

### IAM Role:
Name: IoTWirelessLogsRole
#### Policy Documents:
AWS Managed Document: AWSIoTWirelessLogging
```json
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "logs:CreateLogGroup",
                "logs:CreateLogStream",
                "logs:DescribeLogGroups",
                "logs:DescribeLogStreams",
                "logs:PutLogEvents"
            ],
            "Resource": "arn:aws:logs:*:*:log-group:/aws/iotwireless*"
        }
    ]
}
```
Document created by IoT Core: aws-iot-role-logging_-2072265367
```json
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "logs:CreateLogGroup",
                "logs:CreateLogStream",
                "logs:PutLogEvents",
                "logs:PutMetricFilter",
                "logs:PutRetentionPolicy"
            ],
            "Resource": [
                "arn:aws:logs:*:325286412434:log-group:*:log-stream:*"
            ]
        }
    ]
}
```
Document outlined in logging setup guide: AdditionalIoTLoggingPermissions
```json
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "logs:CreateLogGroup",
                "logs:CreateLogStream",
                "logs:PutLogEvents",
                "logs:PutMetricFilter",
                "logs:PutRetentionPolicy"
            ],
            "Resource": [
                "*"
            ]
        }
    ]
}
```
#### Trust Relationship Document
```json
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Sid": "",
      "Effect": "Allow",
      "Principal": {
        "Service": [
          "iotwireless.amazonaws.com",
          "iot.amazonaws.com"
        ]
      },
      "Action": "sts:AssumeRole"
    }
  ]
}
```

Looking at the [IoT Core for LoRaWAN log entries](https://docs.aws.amazon.com/iot/latest/developerguide/cwl-format.html#iot-lorawan-logs) page. It looks mostly related to errors and message traffic *after* the gateways have been connected. And not gateway connection errors themselves.

**Comment by baxterjo** [comment]
## Update 2
Just read on the [partner catalog page](https://devices.amazonaws.com/detail/a3G0h000007dhzqEAA/Sentrius-RG1xx-LoRaWAN-Gateway) that the Laird Sentrus RG1xx Gateway I am using does not plan to support AWS IoT Core for LoRaWAN until mid-January. Might want to label this "on hold" until they release new firmware.

**Comment by asvand** [comment]
Hello and thanks for using AWS IoT Core for LoRaWAN and contacting us!  As mentioned by yourself, I suggest to put this on-hold till mid-January.  If you wish to be informed immediately after AWS IoT Core for LoRaWAN support for the mentioned gateway is implemented, please send me a direct message with your contact data and I will keep you up-to-date on this matter.

**Comment by baxterjo** [comment]
Github does not support private messaging anymore. But I have notifications for this issue turned on, so posting here would work great. Thank you!

**Comment by asvand** [comment]
Sure, will do!

**Comment by asvand** [comment]
Dear baxterjo, your issue shoud be resolved with the most recent version of the firmware. You will find further documentation and a getting started guide by using links on https://devices.amazonaws.com/detail/a3G0h000007dhzqEAA/Sentrius-RG1xx-LoRaWAN-Gateway. Please kindly update this issue with the outcome and contact me in case of any questions.

**Comment by ivanmorenoj** [comment]
Hi, I'm having the following issue with RG1xx Gateway when i try to connect with AWS IoT core for LoRaWAN.

I followed [this](https://www.lairdconnect.com/documentation/application-note-rg1xx-aws-iot-core-lorawan) guide but when a try to connect with AWS using CUPS appears this error:
![screen1](https://user-images.githubusercontent.com/19803598/119063424-ad654a80-b99e-11eb-976f-89cf6a0b825d.png)

Also I tested using LNS and appears this error:
![screen2](https://user-images.githubusercontent.com/19803598/119063841-9d9a3600-b99f-11eb-9a6a-e20fc2b4173b.png)
