### ISSUE TITLE
missing image

### ISSUE THREAD

**Issue by theguate** [aws-samples/aws-iot-core-lorawan#14]
in this page: https://iotwireless.workshop.aws/es/200_gateway/500_testing.html 
under "3. Verifica el último enlace ascendente recibido, there is an error ( path of the image)

**Comment by asvand** [comment]
Thanks a lot for that hint, we are working of fixing that and I will give you an update as soon as finished!

**Comment by sherlockholmes** [comment]
Working on this...

**Comment by sherlockholmes** [comment]
It should be fixed please perform a hard reload to clean the web browser cache. https://iotwireless.workshop.aws/es/200_gateway/500_testing.html
