### ISSUE TITLE
payload decoder for RAK 7205 example code

### ISSUE THREAD

**Issue by theguate** [aws-samples/aws-iot-core-lorawan#17]
Requesting guidance to get instructions to deploy a rak7200 payload decoder.

**Comment by asvand** [comment]
Hi theguate, unfortunately I lack the hardware to be able to test the decoder. Would you mind following the guidelines in https://github.com/aws-samples/aws-iot-core-lorawan/tree/main/transform_binary_payload#how-to-deploy-an-existing-nodejs-binary-decoder to add a decoder code? As far as I can see, there are several open source versions of decoder available in Node.js. I am happy to review the code and merge it into the repo. Thanks, Andrei
