### ISSUE TITLE
Add example for Arduino MKR WAN 1310

### ISSUE THREAD

**Issue by Nathan904** [aws-samples/aws-iot-core-lorawan#21]

**Comment by asvand** [comment]
Hi Nathan, could you tell more about kind of example you are looking for? What is the use case you are looking at?

**Comment by Nathan904** [comment]
I'm looking for an example to use the Arduino MKR WAN 1310 to send agriculture sensor data to AWS IoT core using LoRaWAN with BasicStation Rg1xx Gateway.

**Comment by asvand** [comment]
Hi Nathan, a first step in build the solution you a looking for is an implementation on the device side. This is indenpendent for used LoRaWAN network server and also typically independent from the used gateway. Once you have finished this this implementation, please let me know the format of the binary payload for agriculture sensor data you intend to use. 

I will be happy to support you ingesting this data to AWS IoT Core for LoRaWAN (once the format is known).

Let me know if you have any questions

**Comment by asvand** [comment]
Hi Nathan, kindly ask you to react to my last message, if the issue is still relevant.
