### ISSUE TITLE
Trying to Connect Yokogawa Suhsi LorWAN sensors to AWS 

### ISSUE THREAD

**Issue by RSWebster** [aws-samples/aws-iot-core-lorawan#25]
Trying to connect Yokogawa XS770A Vibration Sensors to AWS IoT using your LoraWAN workshop flow, I was able to add a RadioBridge Sensor however no data is being pushed to the TEST MQTT. But it does show up connected and is receiving data packets.

**Comment by asvand** [comment]
Hi RSWebster,

thanks for running the workshop and posting your question here! Could you please 
1) let me know if you have built and deployed  a binary decoder for Yokogawa XS770A Vibration Sensors ? Or are you just trying to see the raw binary payload from the sensor on the MQTT topci?
2) double-check that your LoRaWAN Device is assigned a correct AWS IoT Core for LoRaWAN destination?
3) check and post here the configuration of your AWS IoT Core for LoRaWAN Destination?
