### ISSUE TITLE
ST NUCLEO-WL55JC1

### ISSUE THREAD

**Issue by ozzwozz** [aws-samples/aws-iot-core-lorawan#31]

**Comment by asv26617183** [comment]
Hi, could you pls provide more details on that issue? Thanks

**Comment by asvand** [comment]
Hi, could you pls provide more details on that issue?

**Comment by gregbreen** [comment]
I assume it was a request to add a decoder for this board. PR now created.

**Comment by asvand** [comment]
PR merged
